---
title: "group_document"
format: html
---

## Hi team :)

```{r}
#Hey I am ale, this is my section! 
myname <- 'Ale'
print(myname)
```

```{r}
#I'm Carlos, this is my section 
carlos_name <- 'Carlos'
print(carlos_name)
```

```{r}
#New feature
nums <- c(3, 5, 2, 8, 9)
sum(nums)
print(sum)
```

```{r}
#Hey, I am Thelma and this is my section!
numbers <- c(2, 3 , 4)
sum (numbers)
print(sum)

```

# Marco's section

First feature

```{r}
library(tidyverse)

#Hey! I am Marco, this is my section!
df <- data.frame(x = 1:5, y = c(2, 3, 5, 4, 6))

ggplot(df, aes(x, y)) +
  geom_point() +
  geom_line()
```

New feature

```{r}
print("I don't know what to write anymore.")
```
```{r}
#This is Mei Lin section

data = tibble(numbers = c(1,2,3), text = c('A','B','C'))

```

### New features

```{r}
# add vector with big number
data <- data |> merge(
  numbers_big = c(2462,1542,8342)
)
```

#New features_Thelma
```{r}
text <- "Hey guys"
print(text)
```

# Marco's section

First feature

```{r}
library(tidyverse)

#Hey! I am Marco, this is my section!
df <- data.frame(x = 1:5, y = c(2, 3, 5, 4, 6))

ggplot(df, aes(x, y)) +
  geom_point() +
  geom_line()
```

New feature

```{r}
print("I don't know what to write anymore.")
```
```{r}
#This is Mei Lin section

data = tibble(numbers = c(1,2,3), text = c('A','B','C'))

```

### New features

```{r}
# add vector with big number
data <- data |> merge(
  numbers_big = c(2462,1542,8342)
)
```
